version: '3.8'

services:
  db:
    container_name: localbox_db
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localbox_db_local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
